mybatis:
  mapper-locations: mappers/*.xml
server:
  port: 8084
spring:
  shardingsphere:
    datasource:
      master:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3307/test?characterEncoding=utf-8&useSSL=false
        username: root
      names: master,slave1,slave2
      slave1:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3308/test?characterEncoding=utf-8&useSSL=false
        username: root
      slave2:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3308/test?characterEncoding=utf-8&useSSL=false
        username: root
    masterslave:
      load-balance-algorithm-type: round_robin
      master-data-source-name: master
      name: dataSource
      slave-data-source-names: slave1,slave2
    props:
      sql:
        show: true
